env:
  AWS_REGION: ap-southeast-1
  AWS_ROLE_ARN: arn:aws:iam::920252280240:role/S3CDNBucketUploader

agents:
  - "queue=omise-macos-builder"

steps:
  - label: "Distribute iOS XCFrameworks"
    # if: build.tag != null

    plugins:
      - aws-assume-role-with-web-identity#v1.4.0:
          role-arn: "${AWS_ROLE_ARN}"
          role-session-name: "distribute-xcframeworks"
          region: "${AWS_REGION}"

    env:
      AWS_REGION: "ap-southeast-1"
      AWS_DOMAIN: "https://cdn.omise.co/"
      WRAPPER_REPO_DIR: "wrapper_repo"

    command: |
      set -euo pipefail
      echo AWS_ROLE_ARN=$$AWS_ROLE_ARN
      # bash scripts/setup_and_distribute_ios.sh
