steps:
  - label: "Distribute iOS XCFrameworks"
    if: build.tag != null
    agents:
      queue: "macos"

    plugins:
      - aws-assume-role-with-web-identity#v1.4.0:
          role-arn: "${AWS_ROLE_ARN}"
          role-session-name: "distribute-xcframeworks"
          region: "${AWS_REGION}"

    env:
      AWS_S3_BUCKET: "${AWS_S3_BUCKET}"
      AWS_REGION: "${AWS_REGION}"
      AWS_DOMAIN: "${AWS_DOMAIN}"
      GIT_PAT: "${GIT_PAT}"
      WRAPPER_REPO: "${WRAPPER_REPO}"
      WRAPPER_REPO_DIR: "wrapper_repo"
      AWS_ROLE_ARN: "${AWS_ROLE_ARN}"

    command: |
      set -euo pipefail
      bash scripts/setup_and_distribute_ios.sh
